#pragma once

#define EE_HANDS

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#ifdef RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#else
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#endif
